spring:
  application:
    name: greeting-service
    
#Liberando todos os recursos do spring actuator (Não é recomendado deixar tudo exposto em produção)
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
    
greeting-service:
  greeting: "Hello"
  default-value: "Perf"
